baseURL = "https://blog.gabrielsimmer.com/"
languageCode = "en-us"
title = "Gabriel's Blog"
theme = "gs"
ignorefiles = [ "content/posts/exported/.*", "content/posts/drafts/.*" ]
paginate = 5
[markup.goldmark.renderer]
unsafe= true
