#+title: Use RSS
#+date: 2023-03-24

RSS is one of those wonderful technologies that continues to endure, and I genuinely hope that more people realize how useful it can be and embrace the fairly universal sydication format available rather than relying on algorithmically driven aggregators.

For a long time, I've been solely reliant on community-driven link aggregators like HackerNews or Lobste.rs (Reddit as well, although I've long since stopped using it). Why bother visiting sites individually, or seeking out content myself, when I could rely on other people to curate the content? That isn't to say I outright ignored RSS - I still relied on it extensively for podcasts. At some point, I even made a contribution to the [[https://github.com/gorilla/feeds/pull/41][gorilla/feeds project]] for a [[https://github.com/gmemstr/pogo][podcasting platform]] (sidenote: that codebase still works. If I were hosting my own podcast, I'd probably pick it back up). I was really happy with RSS for podcasts, but I wasn't taking it very seriously for articles and blog posts. After all, at that point, I didn't really follow anyone in particular - or if I did, Twitter was all I needed to keep up with them.

Over time, I started to notice a few recurring blogs I consistently read when they cropped up on the aggregators and decided that it was worth following them more closely than a Twitter follow. So, I went and downloaded NetNewsWire and set about adding a few feeds. Along the way, I added the RSS feeds for Lobste.rs and HackerNews - I still found the sites useful and mildly addictive, for varying reasons, and having them unified into a single app was helpful for skimming without the attraction of a large comments section or massive number of votes.

Eventually, the passive adding of interesting RSS feeds caused my collection to grow considerably. Often times a single interesting article from the fediverse or the aggregators will result in the blog being added to my RSS reader. To manage and sync all of them across devices, I was using NetNewsWire's iCloud sync integration, until I started to hit iCloud's rate limits. After an admittedly small amount of research, I opted for [[https://www.freshrss.org/][FreshRSS]] since NetNewsWire supported it natively, and it seemed simple enough to spin up in my homelab Kubernetes cluster. And since that point, it's been happily syncing my RSS feeds and keeping track of what I've read. I have no real notes about FreshRSS - it's a fairly boring and straightforward PHP application, with a reasonable web interface and a handy bookmarklet for subscribing to feeds (it will attempt to parse out the feed URL for a blog page).

It's worth noting that I never had the opportunity to use the apparently wonderful Google Reader, so I have no way of comparing my current setup to what it offered. NetNewsWire is a fairly "dumb" reader, but it does the job well.

At this point I'm subscribed to 48 different feeds for various personal blogs, aggregators, corporate blogs, and webcomics, and I do my best to keep the OPML file up to date [[https://gabrielsimmer.com/feeds.xml][on my website]] if anyone is looking for inspiration. I highly encourage others to /use RSS/ where possible, and preferably with a relatively "dumb" reader that avoids algorithmic curation - or at least offers the ability to ignore it. I also encourage you to subscribe to this blogs own RSS feed! I have a few posts in the pipelines around machine learning and its impacts and implications on code, literary and artistic works. And a post about coffee coming soon.
